# Generated by Django 2.2.5 on 2019-09-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(choices=[('Sanofi', 'Sanofi'), ('Hypera', 'Hypera'), ('Sandoz', 'Sandoz')], max_length=50)),
                ('rede', models.CharField(choices=[('Ultra Popular', 'Ultra Popular'), ('Agafarma', 'Agafarma'), ('Drogaria Total', 'Drogaria Total')], max_length=50)),
                ('dia', models.DateField(default='06/09/2019')),
                ('hora', models.TimeField(default='01:02:41')),
            ],
        ),
    ]
