# Generated by Django 2.2.5 on 2019-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20190906_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='hora',
            field=models.TimeField(default='13:17:10'),
        ),
    ]
